---
# Default variables for the swarm-win role

# Jenkins master URL (adjust as needed)
jenkins_master_url: "http://10.10.102.250:8080"

# Credentials for connecting via swarm
jenkins_swarm_user: "swarmpool"
jenkins_swarm_secret: "1154626d28893d4898fdbc4ee973b13124"

# Destination path for the swarm-client.jar on Windows
swarm_client_dest: "C:\\jenkins\\swarm-client.jar"
