---
- name: Restart Artifactory
  service:
    name: artifactory
    state: restarted

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Restart Artifactory Exporter
  systemd:
    name: artifactory-exporter
    state: restarted
    daemon_reload: yes
