---
# Prometheus configuration
prometheus_version: 3.2.1
prometheus_web_listen_address: "127.0.0.1:9090"
prometheus_storage_retention: "60d"
prometheus_web_external_url: "http://{{ monitoring_server_name }}"
prometheus_db_dir: "/mnt/data/prometheus"

# Nginx configuration
monitoring_nginx_server_name: "{{ monitoring_server_name }}"
monitoring_nginx_proxy_port: 9090

# Jenkins monitoring configuration
jenkins_host: "{{ jenkins_server_name }}"
jenkins_port: 443
jenkins_scheme: "https"
jenkins_tls_skip_verify: false  # Set to true if using self-signed certificates
