---
- name: Enable auto-logon for the user
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: "1"
    type: string
    state: present

- name: Set default username for auto-logon
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    data: "{{ ansible_user }}"
    type: string
    state: present

- name: Set default password for auto-logon
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: "{{ auto_logon_password }}"
    type: string
    state: present

- name: Set default domain name for auto-logon (if needed)
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultDomainName
    data: "{{ ansible_hostname }}"
    type: string
    state: present

