---
- name: Install OpenJDK 17 via Chocolatey
  win_chocolatey:
    name: openjdk17
    state: present

- name: Add OpenJDK bin directory to user PATH using PowerShell
  win_shell: |
    $currentPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::User)
    if ($currentPath -notlike '*C:\Program Files\OpenJDK\jdk-17\bin*') {
        $newPath = $currentPath + ';C:\Program Files\OpenJDK\jdk-17\bin'
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::User)
    }

- name: Reload user environment variables
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::User)

