---
- name: Ensure the swarm working directory exists on Windows
  win_file:
    path: "{{ swarm_working_dir }}"
    state: directory

- name: Create desktop shortcut for working dir
  win_shortcut:
    src: "{{ swarm_working_dir }}"
    dest: "C:\\Users\\{{ ansible_user }}\\Desktop\\Jenkins.lnk"
    description: "Jenkins Working Directory"

- name: Download Jenkins Swarm client jar
  win_get_url:
    url: "{{ jenkins_master_url }}/swarm/swarm-client.jar"
    dest: "{{ swarm_client_dest }}"
    url_username: "{{ jenkins_swarm_user }}"
    url_password: "{{ jenkins_swarm_secret }}"
  register: swarm_jar

- name: Create the start-swarm-agent.bat file from template
  win_template:
    src: start-swarm-agent.bat.j2
    dest: "{{ swarm_working_dir }}\\start-swarm-agent.bat"

- name: Create a scheduled task to run the swarm agent at user logon
  win_scheduled_task:
    name: "Start Jenkins Swarm Agent"
    actions:
      - path: "{{ swarm_working_dir }}\\start-swarm-agent.bat"
        working_directory: "{{ swarm_working_dir }}"
    triggers:
      - type: logon
        user_id: "{{ ansible_user }}"
    username: "{{ ansible_user }}"
    run_only_if_logged_on: yes
    state: present

- name: Force Restart Jenkins Swarm Agent to pick up new parameters
  block:
    - name: Stop Jenkins Swarm Agent via scheduled task
      win_command: schtasks /end /tn "Start Jenkins Swarm Agent"
      ignore_errors: yes
      register: stop_task

    - name: Start Jenkins Swarm Agent via scheduled task
      win_command: schtasks /run /tn "Start Jenkins Swarm Agent"
      ignore_errors: yes
      register: start_task

    - name: Debug stop task output
      debug:
        var: stop_task.stdout

    - name: Debug start task output
      debug:
        var: start_task.stdout
  when: swarm_force_restart | default(true)

