---
- name: Install Windows Exporter using Chocolatey
  win_chocolatey:
    name: prometheus-windows-exporter.install
    state: present
  register: exporter_install

- name: Wait for Windows Exporter service to start
  win_service:
    name: windows_exporter
    state: started
  register: exporter_service
  until: exporter_service.state == "running"
  retries: 5
  delay: 5

- name: Verify Windows Exporter is accessible
  win_uri:
    url: http://localhost:9182/metrics
    method: GET
    return_content: no
    status_code: 200
  register: exporter_check
  failed_when: exporter_check.status_code != 200

- name: Add firewall rule for Windows Exporter
  win_firewall_rule:
    name: "Windows Exporter (Prometheus)"
    description: "Allow Prometheus to scrape Windows metrics"
    localport: 9182
    action: allow
    direction: in
    protocol: tcp
    enabled: yes
    profiles: [Domain, Private, Public]

