---
- name: Install Git Bash via Chocolatey
  win_chocolatey:
    name: git
    state: present

- name: Add Git directory to system PATH using PowerShell
  win_shell: |
    $currentPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)
    if ($currentPath -notlike '*C:\Program Files\Git\cmd*') {
        $newPath = $currentPath + ';C:\Program Files\Git\cmd'
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::Machine)
    }

- name: Reload environment variables
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)

- name: Check Git version
  win_shell: git --version
  register: git_version

- name: Show Git version
  debug:
    msg: "{{ git_version.stdout }}"

