---
- name: Install Git Bash via Chocolatey
  win_chocolatey:
    name: git
    state: present

- name: Add Git directory to system PATH using PowerShell
  win_shell: |
    $currentPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::User)
    if ($currentPath -notlike '*C:\Program Files\Git\bin*') {
        $newPath = $currentPath + ';C:\Program Files\Git\bin'
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::User)
    }

- name: Reload environment variables
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)

