---
- name: Install UnxUtils via Chocolatey
  win_chocolatey:
    name: unxutils
    state: present

- name: Add UnxUtils directory to system PATH using PowerShell
  win_shell: |
    $currentPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)
    if ($currentPath -notlike '*C:\ProgramData\chocolatey\lib\unxUtils\tools\unxUtils\usr\local\wbin*') {
        $newPath = $currentPath + ';C:\ProgramData\chocolatey\lib\unxUtils\tools\unxUtils\usr\local\wbin'
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::Machine)
    }

- name: Reload environment variables
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)

# Needed to browse commands in bash shell using PgDn and PgUp
- name: Copy .inputrc to home directory
  win_copy:
    src: files/.inputrc
    dest: "{{ ansible_env.USERPROFILE }}\\.inputrc"

