---
- name: Install Vim (version 9.1.990) via Chocolatey
  win_chocolatey:
    name: vim
    version: 9.1.990
    state: present

- name: Add Vim directory to system PATH using PowerShell
  win_shell: |
    $currentPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)
    if ($currentPath -notlike '*C:\tools\vim\vim91*') {
        $newPath = $currentPath + ';C:\tools\vim\vim91'
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::Machine)
    }

- name: Reload environment variables
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)

- name: Copy .vimrc to home directory
  win_copy:
    src: files/.vimrc
    dest: "{{ ansible_env.USERPROFILE }}\\.vimrc"

