---
# PostegreSQL installation parameters
postgres_enabled: true

# Artifactory installation parameters
artifactory_enabled: true
# artifactory_version: "7.x"
artifactory_install_dir: "/opt/jfrog/artifactory"
artifactory_data_dir: "/mnt/artifacts"
artifactory_default_data_dir: "/var/opt/jfrog/artifactory"
artifactory_security_dir: "{{ artifactory_default_data_dir }}/etc/security"
artifactory_service_name: "artifactory"
artifactory_user: "artifactory"
artifactory_group: "artifactory"

# Specify that we want the OSS version instead of PRO
artifactory_product: oss
artifactory_version: "7.104.6"
artifactory_full_version: "jfrog-artifactory-oss-{{ artifactory_version }}-linux.tar.gz"
artifactory_tar_file_name: "jfrog-artifactory-oss-{{ artifactory_version }}-linux.tar.gz"
artifactory_tar: "https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/{{ artifactory_version }}/{{ artifactory_tar_file_name }}"
artifactory_untar_home: "/opt/jfrog/artifactory-oss-{{ artifactory_version }}/"

force_master_key_creation: false
master_key: "/var/opt/jfrog/artifactory/etc/security/master.key"

# Specify cluster configuration - standalone installation, no other nodes
artifactory_cluster_enabled: false
artifactory_cluster_joinKey: ""
artifactory_cluster_nodeType: standalone

# Database configuration for PostgreSQL used by Artifactory
postgres_driver_download: true
database:
  default:
    type: "postgresql"
    host: "localhost"
    port: 5432
    name: "artifactory"
    username: "artifactory"
    password: "{{ artifactory_database_password }}"
    owner: "artifactory"
    enabled: true

# Nginx reverse proxy configuration
artifactory_nginx_ssl_enabled: true
ssl_certificate_install: false
ssl_certificate_path: "/etc/nginx/ssl"
ssl_certificate_key_path: "/etc/nginx/ssl"
ssl_certificate: "reconart_net_chain.crt"
ssl_certificate_key: "wildcard_reconart_net.key"
certificate: "{{ ssl_certificate }}"
certificate_key: "{{ ssl_certificate_key }}"
artifactory_upstream_url: "http://127.0.0.1:8081/artifactory/"

