---
- include_tasks: set_hostname.yml
- include_tasks: install_jenkins.yml
- include_tasks: configure_swarm.yml
- include_tasks: service.yml
- include_tasks: install_nginx.yml
- include_tasks: install_tools.yml

# The following tasks are not complete
# and must be run after Jenkins is up and running
#- include_tasks: jenkins_plugins.yml
#- include_tasks: create_swarmpool.yml
