---
# Pre-check tasks for Artifactory installation

- name: Ensure /mnt/artifacts directory exists
  file:
    path: /mnt/artifacts
    state: directory

- name: Assert that /mnt/artifacts is a mount point
  assert:
    that:
      - (ansible_mounts | selectattr('mount', 'equalto', '/mnt/artifacts') | list) | length > 0
    fail_msg: "/mnt/artifacts is not a mount point. Please ensure the disk is mounted at /mnt/artifacts."

- name: Retrieve /mnt/artifacts mount info
  set_fact:
    artifacts_mount: "{{ (ansible_mounts | selectattr('mount', 'equalto', '/mnt/artifacts') | list)[0] }}"

- name: Assert /mnt/artifacts has at least 1TB capacity
  assert:
    that:
      - artifacts_mount.size_total | int >= 1099511627776
    fail_msg: "/mnt/artifacts capacity is insufficient ({{ artifacts_mount.size_total }} bytes). It must be at least 1TB."

