---
# Install and configure Node.js
- name: Install Node.js
  win_chocolatey:
    name: nodejs-lts
    state: present

- name: Add Node.js directory to system PATH
  win_shell: |
    $currentPath = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)
    if ($currentPath -notlike '*C:\Program Files\nodejs*') {
        $newPath = $currentPath + ';C:\Program Files\nodejs'
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::Machine)
    }

- name: Reload environment variables
  win_shell: |
    $env:Path = [System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::Machine)
