---
- name: Install Windows build machines
  hosts: build_win
  become: yes
  become_user: administrator
  vars:
    ansible_user: administrator
    ansible_ssh_private_key_file: ~/.ssh/bootstrap_rsa
    ansible_connection: ssh
    ansible_remote_tmp: C:\ansible_temp
    ansible_shell_type: powershell
    ansible_shell_executable: powershell
    ansible_python_interpreter: C:\Python313\python.exe
    swarm_labels: build_ra
  tasks:
    - name: Check access
      win_ping:
  roles:
    - common-win
    - build-win
    - swarm-win

- name: Setup Jenkins host
  hosts: jenkins_servers
  become: yes
  vars:
    ansible_user: bootstrap
    ansible_ssh_private_key_file: ~/.ssh/bootstrap_rsa
    ansible_connection: ssh
  roles:
    - jenkins-host

