---
- name: Test connections to windows hosts and install Git Bash
  hosts: windows
  tasks:
    - name: Check access
      win_ping:

    - name: Install Git Bash via Chocolatey
      win_chocolatey:
        name: git
        state: present
      become: yes
      become_user: bootstrap

    - name: Ensure Git is in the PATH
      win_environment:
        name: PATH
        value: 'C:\Program Files\Git\cmd'
        level: user
        state: present

    - name: Check Git version
      win_command: git --version
      register: git_version

    - name: Show Git version
      debug:
        var: git_version.stdout

