---
- name: Run setup on Windows host
  hosts: build_win
  vars:
    ansible_user: administrator
    ansible_ssh_private_key_file: ~/.ssh/bootstrap_rsa
    ansible_connection: ssh
    ansible_remote_tmp: C:\\ansible_temp
    ansible_shell_type: powershell
    ansible_shell_executable: powershell
    ansible_python_interpreter: C:\\Python313\\python.exe

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Debug OS name
      ansible.builtin.debug:
        var: ansible_facts.os_name

    - name: Debug OS product type
      ansible.builtin.debug:
        var: ansible_facts.os_product_type

